openapi: 3.0.3
info:
  title: Example-Api-Users
  version: 1.0.0
  description: Example API to demonstrate the working for Swagger
  termsOfService: https://company.com/terms
  contact:
    email: company@example.com
    name: Company
    url: https://company.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https:/localhost:8080
    variables: {}
    description: 'Local Server development '
tags:
  - name: user
    description: Everything about users
paths:
  /users:
    summary: Everything about users will fetch
    get:
      summary: Get Users inofrmation`
      description: Returns list of users
      operationId: listUsers
      responses:
        '200':
          content:
            application/json:
              examples:
                A List of Users:
                  value: |-
                    [
                     {
                       "id":"1",
                       "email":"mathan@123.in",
                       "name" :"mathankumar"
                     },
                    {
                       "id":"2",
                       "email":"siranjeevi@123.in",
                       "name" :"Siranjeevi"
                     }
                    ]
        '204':
          description: Default error sample response
      tags:
        - user
components:
  schemas:
    User:
      type: object
      properties: 
        id:
          type: integer
          format: int64
          example : 1
        email:
          type : String 
          example : example@email.com
        name:
          type: String
          example: Mathankumar
      
      
      
